const CONFIG_SERVER = 'config-server'
const ENV_BUILD_WHERE_PRODUCE = 'PRODUCE'
const ENV_BUILD_WHERE_DEBUG_OFFICE = 'DEBUG_OFFICE'
const ENV_BUILD_WHERE_DEBUG_HOME = 'DEBUG_HOME'
const ENV_BUILD_TARGET_WSY = 'WSY'
const ENV_BUILD_TARGET_BC = 'BC'
const ACCESS_TOKEN_NAME = 'access_token'
const SESSION_KEY_NAME = 'gen_session_key'
const SERVER_GEN = 'server-gen'
const NEW_ADDED = 'new_added'
const ORDER_CONFIRM_NOW = 'order-confirm-now'
const ORDER_IS_CHANGED = 'order-is-changed'


module.exports = {
    CONFIG_SERVER,
    ENV_BUILD_WHERE_PRODUCE,
    ENV_BUILD_WHERE_DEBUG_OFFICE,
    ENV_BUILD_WHERE_DEBUG_HOME,
    ENV_BUILD_TARGET_WSY,
    ENV_BUILD_TARGET_BC,
    SESSION_KEY_NAME,
    SERVER_GEN,
    NEW_ADDED,
    ORDER_CONFIRM_NOW,
    ORDER_IS_CHANGED
}